export const CONSTRAINTS = {
  BOTTOM_SHEET_CLOSE_THRESHOLD: 20,
  HEADER_HIDE_SCROLL_THRESHOLD: 10,
  SNACKBAR_CLOSE_THRESHOLD: 80,

  SIGN_UP: {
    ARTIST_NAME_MAX_LENGTH: 20,
  },
};

export const LAYOUT = {
  SIDE_PADDING: 16,
  SECTION_GAP: 20,
  CARD_GAP: 8,
};
