export const CONSTRAINTS = {
  BOTTOM_SHEET_CLOSE_THRESHOLD: 20,
  HEADER_HIDE_SCROLL_THRESHOLD: 10,
  SNACKBAR_CLOSE_THRESHOLD: 80,

  SIGN_UP: {
    ARTIST_NAME_MAX_LENGTH: 20,
  },

  PROFILE: {
    NICKNAME_MAX_LENGTH: 10,
    INTRO_MAX_LENGTH: 50,
  },

  PRODUCT: {
    TITLE_MAX_LENGTH: 50,
    AUTHOR_NAME_MAX_LENGTH: 35,
    DESCRIPTION_MAX_LENGTH: 200,
    VIDEO_URL_MAX_LENGTH: 500,
    MAX_PHOTO_COUNT: 10,
  },

  GUEST_BOOK_WRITE: {
    NICKNAME_MAX_LENGTH: 20,
    MESSAGE_MAX_LENGTH: 400,
    MAX_PHOTO_COUNT: 10,
  },

  CREATE_SPACE: {
    NAME_MAX_LENGTH: 50,
    DESCRIPTION_MAX_LENGTH: 200,
  },

  IMAGE: {
    /** presigned URL 업로드용 webp 변환 시 긴 변 최대 길이(px) */
    UPLOAD_MAX_DIMENSION: 1920,
    /** presigned URL 업로드용 webp 변환 품질(0~1) */
    UPLOAD_QUALITY: 0.9,
  },

  GUEST_BOOK_LIST: {
    PAGE_SIZE: 20,
  },
};
