/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Forgather API
 * 당신을 위한 순간, 흩어지지 않게. Forgather
 * OpenAPI spec version: 2.0.0
 */
import type { ApiResponsePublicHostProfileResponseCode } from './apiResponsePublicHostProfileResponseCode';
import type { PublicHostProfileResponse } from './publicHostProfileResponse';

export interface ApiResponsePublicHostProfileResponse {
  code?: ApiResponsePublicHostProfileResponseCode;
  message?: string;
  data?: PublicHostProfileResponse;
}
