/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Forgather API
 * 당신을 위한 순간, 흩어지지 않게. Forgather
 * OpenAPI spec version: 2.0.0
 */

export interface AppleLoginConfirmRequest {
  /** 클라이언트가 받은 Apple identity token */
  id_token?: string;
  /** Apple authorization code */
  authorization_code?: string;
  /** Apple 요청에 사용한 nonce의 원본 문자열 */
  raw_nonce?: string;
  /** Apple 최초 동의 시 받은 이름 구성요소를 클라이언트에서 조합한 문자열 */
  full_name?: string;
}
