/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Forgather API
 * 당신을 위한 순간, 흩어지지 않게. Forgather
 * OpenAPI spec version: 2.0.0
 */

export interface CheckSpaceHostResponse {
  /** 스페이스 호스트 여부, true일 경우 스페이스의 호스트가 맞다 */
  isSpaceHost?: boolean;
}
