/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Forgather API
 * 당신을 위한 순간, 흩어지지 않게. Forgather
 * OpenAPI spec version: 2.0.0
 */

/**
 * 생성자 호스트 정보
 */
export interface CreatorInfo {
  /** 전시 호스트(작가) ID */
  id?: number;
  /** 전시 호스트(작가) 이름 */
  name?: string;
}
