/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Forgather API
 * 당신을 위한 순간, 흩어지지 않게. Forgather
 * OpenAPI spec version: 2.0.0
 */

/**
 * 전시 대표 이미지 (선택, null 가능)
 */
export interface CreateExhibitionPhotoRequest {
  /** 업로드 파일명 (UUID.확장자) */
  uploadFileName: string;
  /** 전시 이미지 파일 크기 (bytes) */
  capacity: number;
}
