/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Forgather API
 * 당신을 위한 순간, 흩어지지 않게. Forgather
 * OpenAPI spec version: 2.0.0
 */
import type { CreateExhibitionPhotoRequest } from './createExhibitionPhotoRequest';
import type { LocationRequest } from './locationRequest';
import type { OperatingHourRequest } from './operatingHourRequest';

export interface CreateExhibitionRequest {
  photo?: CreateExhibitionPhotoRequest;
  /**
   * 전시 제목 (최대 100자)
   * @maxLength 100
   */
  title: string;
  /** 시작일 */
  startDate: string;
  /** 종료일 */
  endDate: string;
  /**
   * 전시 소개 (최대 200자, null 가능)
   * @maxLength 200
   * @nullable
   */
  description?: string | null;
  /**
   * 운영 공지 (최대 200자, null 가능)
   * @maxLength 200
   * @nullable
   */
  operationNotice?: string | null;
  /**
   * 운영하는 요일별 시간. 같은 요일 중복 금지. 최대 7개. (null 가능)
   * @minItems 0
   * @maxItems 7
   */
  operatingHours?: OperatingHourRequest[];
  location?: LocationRequest;
}
