/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Forgather API
 * 당신을 위한 순간, 흩어지지 않게. Forgather
 * OpenAPI spec version: 2.0.0
 */

/**
 * 신고 사유 코드
- ADVERTISEMENT_SPAM: 광고/홍보/스팸
- ABUSE_HARASSMENT: 욕설/비방/괴롭힘
- HATE_DISCRIMINATION: 차별/혐오 표현
- SEXUAL_CONTENT: 음란/선정적 내용
- REPETITIVE_CONTENT: 도배/반복 게시
- PERSONAL_INFORMATION_EXPOSURE: 개인정보/민감정보 노출
- ILLEGAL_DANGEROUS_CONTENT: 불법/위험 행위 또는 악성 링크
- OTHER: 기타

 */
export type CreateGuestBookReportRequestReason = typeof CreateGuestBookReportRequestReason[keyof typeof CreateGuestBookReportRequestReason];


export const CreateGuestBookReportRequestReason = {
  ADVERTISEMENT_SPAM: 'ADVERTISEMENT_SPAM',
  ABUSE_HARASSMENT: 'ABUSE_HARASSMENT',
  HATE_DISCRIMINATION: 'HATE_DISCRIMINATION',
  SEXUAL_CONTENT: 'SEXUAL_CONTENT',
  REPETITIVE_CONTENT: 'REPETITIVE_CONTENT',
  PERSONAL_INFORMATION_EXPOSURE: 'PERSONAL_INFORMATION_EXPOSURE',
  ILLEGAL_DANGEROUS_CONTENT: 'ILLEGAL_DANGEROUS_CONTENT',
  OTHER: 'OTHER',
} as const;
