/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Forgather API
 * 당신을 위한 순간, 흩어지지 않게. Forgather
 * OpenAPI spec version: 2.0.0
 */

export interface CreateSpaceRequest {
  /**
   * 스페이스 이름
   * @maxLength 30
   */
  name: string;
  /**
   * 스페이스 설명
   * @maxLength 200
   * @nullable
   */
  description?: string | null;
  /** 스페이스 공개 여부 */
  isPublic?: boolean;
  /**
   * 스페이스 소개 링크 URL (표시 이름과 함께 입력)
   * @maxLength 2048
   * @nullable
   */
  linkUrl?: string | null;
  /**
   * 스페이스 소개 링크 표시 이름 (URL과 함께 입력)
   * @maxLength 30
   * @nullable
   */
  linkName?: string | null;
}
