/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Forgather API
 * 당신을 위한 순간, 흩어지지 않게. Forgather
 * OpenAPI spec version: 2.0.0
 */

export interface DevLoginRequest {
  /** 개발용 임시 로그인 아이디 */
  loginId?: string;
  /** 개발용 임시 로그인 비밀번호 */
  password?: string;
}
