/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Forgather API
 * 당신을 위한 순간, 흩어지지 않게. Forgather
 * OpenAPI spec version: 2.0.0
 */
import type { CreatorInfo } from './creatorInfo';
import type { ExhibitionResponseProgressStatus } from './exhibitionResponseProgressStatus';
import type { LocationResponse } from './locationResponse';
import type { OperatingHourResponse } from './operatingHourResponse';

export interface ExhibitionResponse {
  /** 전시 ID */
  id?: number;
  /** 전시 제목 */
  title?: string;
  /** 전시 소개 (미설정 시 null) */
  description?: string;
  /** 운영 공지 (미설정 시 null) */
  operationNotice?: string;
  /** 대표 이미지 경로 (미설정 시 null) */
  photoPath?: string;
  /** 시작일 */
  startDate?: string;
  /** 종료일 */
  endDate?: string;
  /** 진행 상태 (KST 기준 오늘 날짜로 계산) */
  progressStatus?: ExhibitionResponseProgressStatus;
  /** 운영 시간 (미설정 시 null, 운영 요일만 MONDAY~SUNDAY 순으로 포함) */
  operatingHours?: OperatingHourResponse[];
  location?: LocationResponse;
  creator?: CreatorInfo;
  /** 생성 일시 */
  createdAt?: string;
}
