/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Forgather API
 * 당신을 위한 순간, 흩어지지 않게. Forgather
 * OpenAPI spec version: 2.0.0
 */

/**
 * 진행 상태 (KST 기준 오늘 날짜로 계산)
 */
export type ExhibitionResponseProgressStatus = typeof ExhibitionResponseProgressStatus[keyof typeof ExhibitionResponseProgressStatus];


export const ExhibitionResponseProgressStatus = {
  UPCOMING: 'UPCOMING',
  IN_PROGRESS: 'IN_PROGRESS',
  ENDED: 'ENDED',
} as const;
