/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Forgather API
 * 당신을 위한 순간, 흩어지지 않게. Forgather
 * OpenAPI spec version: 2.0.0
 */

export interface FeatureSpacesRequest {
  /**
   * '지금 축하받고 있는 스페이스'로 지정할 스페이스 코드 목록. 1개 이상 100개 이하. 요청에 포함되지 않은 스페이스의 지정 상태는 변경되지 않습니다.
   * @minItems 1
   * @maxItems 100
   */
  spaceCodes: string[];
}
