/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Forgather API
 * 당신을 위한 순간, 흩어지지 않게. Forgather
 * OpenAPI spec version: 2.0.0
 */

/**
 * 방명록 카드 목록
 */
export interface GuestBookCardSimpleResponse {
  id?: number;
  /** 방문자 닉네임 */
  nickname?: string;
  /** 메세지 */
  message?: string;
  /** 방명록 카드 생성 시각 */
  createdAt?: string;
  /** 사진 포함 여부 */
  containsPhoto?: boolean;
  /** 호스트 읽음 여부 */
  isRead?: boolean;
}
