/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Forgather API
 * 당신을 위한 순간, 흩어지지 않게. Forgather
 * OpenAPI spec version: 2.0.0
 */

export interface HostResponse {
  /** 호스트 ID */
  id?: number;
  /** 호스트 이름 */
  name?: string;
  /** 호스트 프로필 사진 URL */
  pictureUrl?: string;
  /** 약관 동의 여부 */
  agreedTerms?: boolean;
}
