/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Forgather API
 * 당신을 위한 순간, 흩어지지 않게. Forgather
 * OpenAPI spec version: 2.0.0
 */

export interface HostProfileResponse {
  /** 닉네임 */
  nickname?: string;
  /** 한 줄 소개 */
  introduction?: string;
  /** 링크 URL */
  linkUrl?: string;
  /** 프로필 사진 URL */
  pictureUrl?: string;
}
