/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Forgather API
 * 당신을 위한 순간, 흩어지지 않게. Forgather
 * OpenAPI spec version: 2.0.0
 */
import type { IssueSignedUrlRequestCategory } from './issueSignedUrlRequestCategory';

export interface IssueSignedUrlRequest {
  /** 업로드 파일 카테고리 */
  category?: IssueSignedUrlRequestCategory;
  /** 업로드 파일 이름 목록 */
  uploadFileNames?: string[];
}
