/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Forgather API
 * 당신을 위한 순간, 흩어지지 않게. Forgather
 * OpenAPI spec version: 2.0.0
 */

export interface KakaoLoginConfirmRequest {
  /** 사용자 액세스 토큰 */
  access_token?: string;
  /** 토큰 타입 */
  token_type?: string;
  /** 사용자 리프레시 토큰 */
  refresh_token?: string;
  /** ID 토큰 */
  id_token?: string;
  /** 카카오 로그인 요청에 사용한 nonce의 원본 문자열. 클라이언트는 이 값을 SHA-256 해싱한 결과를 카카오 SDK에 nonce로 전달해야 한다. */
  raw_nonce?: string;
  /** 액세스 토큰과 ID 토큰의 만료 시간(초) */
  expires_in?: number;
  /** 인증된 사용자의 정보 조회 권한 범위 */
  scope?: string;
  /** 리프레시 토큰 만료 시간(초) */
  refresh_token_expires_in?: string;
}
