/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Forgather API
 * 당신을 위한 순간, 흩어지지 않게. Forgather
 * OpenAPI spec version: 2.0.0
 */
import type { LocationResponseLocationType } from './locationResponseLocationType';

/**
 * 장소 (미설정 시 null)
 */
export interface LocationResponse {
  /** 장소 타입 */
  locationType?: LocationResponseLocationType;
  /** 온라인 URL (ONLINE 타입일 때만 값 존재, 그 외 null) */
  url?: string;
  /** 기본 주소 (OFFLINE 타입일 때만 값 존재, 그 외 null) */
  baseAddress?: string;
  /** 상세 주소 (OFFLINE 타입일 때 선택, 미입력 시 null) */
  detailAddress?: string;
}
