/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Forgather API
 * 당신을 위한 순간, 흩어지지 않게. Forgather
 * OpenAPI spec version: 2.0.0
 */

/**
 * 장소 타입
 */
export type LocationRequestLocationType = typeof LocationRequestLocationType[keyof typeof LocationRequestLocationType];


export const LocationRequestLocationType = {
  ONLINE: 'ONLINE',
  OFFLINE: 'OFFLINE',
} as const;
