/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Forgather API
 * 당신을 위한 순간, 흩어지지 않게. Forgather
 * OpenAPI spec version: 2.0.0
 */
import type { LocationRequestLocationType } from './locationRequestLocationType';

/**
 * 장소 정보 (null 가능)
 */
export interface LocationRequest {
  /** 장소 타입 */
  locationType: LocationRequestLocationType;
  /** 온라인 URL (ONLINE 타입일 때 필수) */
  url?: string;
  /** 기본 주소 (OFFLINE 타입일 때 필수) */
  baseAddress?: string;
  /** 상세 주소 (OFFLINE 타입일 때 선택, null 가능) */
  detailAddress?: string;
}
