/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Forgather API
 * 당신을 위한 순간, 흩어지지 않게. Forgather
 * OpenAPI spec version: 2.0.0
 */

export interface OnboardingRequest {
  /** 서비스 닉네임 */
  nickname?: string;
  /** 동의한 약관 ID 목록 */
  agreedTermIds?: number[];
  /** 거절한 약관 ID 목록. 모든 약관 타입에 대해 동의 또는 거절 결정이 명시되어야 하며, 필수 약관은 거절할 수 없습니다. */
  rejectedTermIds?: number[];
}
