/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Forgather API
 * 당신을 위한 순간, 흩어지지 않게. Forgather
 * OpenAPI spec version: 2.0.0
 */

export interface OnboardingRequest {
  /** 서비스 닉네임 */
  nickname?: string;
  /** 동의한 약관 ID 목록 */
  agreedTermIds?: number[];
}
