/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Forgather API
 * 당신을 위한 순간, 흩어지지 않게. Forgather
 * OpenAPI spec version: 2.0.0
 */
import type { LocalTime } from './localTime';
import type { OperatingHourRequestDayOfWeek } from './operatingHourRequestDayOfWeek';

export interface OperatingHourRequest {
  /** 운영 요일 */
  dayOfWeek: OperatingHourRequestDayOfWeek;
  startTime: LocalTime;
  endTime: LocalTime;
}
