/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Forgather API
 * 당신을 위한 순간, 흩어지지 않게. Forgather
 * OpenAPI spec version: 2.0.0
 */

/**
 * 작품 관련 사진들
 */
export interface ProductPhotoResponse {
  /** 사진 id */
  id?: number;
  /** 원본 파일명 */
  originalName?: string;
  /** S3 파일 경로 */
  path?: string;
  /** 사진 정렬 순서 */
  order?: number;
}
