/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Forgather API
 * 당신을 위한 순간, 흩어지지 않게. Forgather
 * OpenAPI spec version: 2.0.0
 */

/**
 * 새로 업로드한 프로필 사진. 전달하면 기존 사진을 교체한다.
 * @nullable
 */
export type RegisterHostProfilePhotoRequest = {
  /**
   * 업로드 파일 이름 (UUID.확장자)
   * @pattern ^[^/\\]+\.[a-z0-9]+$
   */
  uploadFileName: string;
  /**
   * 업로드 파일 크기 (바이트)
   * @maximum 20971520
   */
  capacity: number;
} | null;
