/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Forgather API
 * 당신을 위한 순간, 흩어지지 않게. Forgather
 * OpenAPI spec version: 2.0.0
 */
import type { SpaceInfo } from './spaceInfo';

export interface ReportDetailResponse {
  id?: number;
  space?: SpaceInfo;
  reason?: string;
  detail?: string;
  nicknameSnapshot?: string;
  messageSnapshot?: string;
  createdAtSnapshot?: string;
  createdAt?: string;
}
