/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Forgather API
 * 당신을 위한 순간, 흩어지지 않게. Forgather
 * OpenAPI spec version: 2.0.0
 */

export interface ReportHistoryDto {
  id?: number;
  /** 신고 당시 방명록 작성 닉네임 */
  nicknameSnapshot?: string;
  /** 신고 당시 방명록 내용 */
  messageSnapshot?: string;
  /** 신고 접수 시각 */
  createdAt?: string;
}
