/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Forgather API
 * 당신을 위한 순간, 흩어지지 않게. Forgather
 * OpenAPI spec version: 2.0.0
 */
import type { Pageable } from './pageable';

export type RetrieveReportHistoryParams = {
/**
 * 페이지 번호 (1부터 시작)
 * @minimum 1
 */
page?: number;
/**
 * 페이지 크기
 * @minimum 1
 */
size?: number;
/**
 * 정렬 조건 (여러개 지정 가능) (id,desc 포함 필수)
 */
sort?: string[];
pageable: Pageable;
};
