/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Forgather API
 * 당신을 위한 순간, 흩어지지 않게. Forgather
 * OpenAPI spec version: 2.0.0
 */
import type { ProductPhotoResponse } from './productPhotoResponse';

export interface SimpleProductResponse {
  /** 작품 id */
  id?: number;
  /** 작품명 */
  title?: string;
  /** 임베드 영상 링크 */
  videoUrl?: string;
  firstPhoto?: ProductPhotoResponse;
}
