/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Forgather API
 * 당신을 위한 순간, 흩어지지 않게. Forgather
 * OpenAPI spec version: 2.0.0
 */

/**
 * 스페이스 프로필 사진
 */
export interface SpacePhotoResponse {
  /** 스페이스 프로필 존재 여부 */
  isExists?: boolean;
  /** 스페이스 프로필 경로 */
  path?: string;
}
