/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Forgather API
 * 당신을 위한 순간, 흩어지지 않게. Forgather
 * OpenAPI spec version: 2.0.0
 */
import type { SpacePhotoResponse } from './spacePhotoResponse';

export interface SpaceResponse {
  /** 스페이스 ID */
  id?: number;
  /** 스페이스 코드 */
  spaceCode?: string;
  /** 스페이스 이름 */
  name?: string;
  /** 스페이스 설명 */
  description?: string;
  /** 스페이스 공개여부 */
  isPublic?: boolean;
  /** 스페이스 호스트 인스타그램 아이디 */
  instagramUsername?: string;
  /** 스페이스 호스트 이메일 */
  email?: string;
  /** 스페이스 소개 링크 URL */
  linkUrl?: string;
  /** 스페이스 소개 링크 표시 이름 */
  linkName?: string;
  spacePhoto?: SpacePhotoResponse;
  /** 스페이스 방명록 카드 개수 */
  guestBookCardCount?: number;
}
