/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Forgather API
 * 당신을 위한 순간, 흩어지지 않게. Forgather
 * OpenAPI spec version: 2.0.0
 */

export interface TermResponse {
  /** 약관 id */
  id?: number;
  /** 약관 타입 */
  type?: string;
  /** 약관 이름 */
  name?: string;
  /** 약관 버전 */
  version?: string;
  /** Markdown 형식의 약관 본문 */
  content?: string;
  /** 필수 동의 여부 */
  isRequired?: boolean;
  /** 노출 순서 */
  sortOrder?: number;
}
