/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Forgather API
 * 당신을 위한 순간, 흩어지지 않게. Forgather
 * OpenAPI spec version: 2.0.0
 */

export interface TermAgreementResponse {
  /** 약관 id */
  id?: number;
  /** 약관 타입 */
  type?: string;
  /** 약관 이름 */
  name?: string;
  /** 약관 버전 */
  version?: string;
  /** Markdown 형식의 약관 본문 */
  content?: string;
  /** 필수 동의 여부 */
  isRequired?: boolean;
  /** 노출 순서 */
  sortOrder?: number;
  /** 현재 유효한 동의 여부 */
  isAgreed?: boolean;
  /** 동의 일시. 유효한 동의가 없으면 null */
  agreedAt?: string;
  /** 재동의 필요 여부. 필수 타입은 유효한 동의가 없으면 true, 선택 타입은 동의했었으나 개정으로 무효화된 경우에만 true */
  isReagreementRequired?: boolean;
}
