/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Forgather API
 * 당신을 위한 순간, 흩어지지 않게. Forgather
 * OpenAPI spec version: 2.0.0
 */

/**
 * 프로필 수정 요청. null인 필드는 변경하지 않고, 빈 문자열은 값을 제거한다. (닉네임은 빈 문자열 불가)
 */
export interface UpdateHostProfileRequest {
  /**
   * 닉네임 (최대 10자)
   * @nullable
   */
  nickname?: string | null;
  /**
   * 한 줄 소개 (최대 50자, 빈 문자열이면 제거)
   * @nullable
   */
  introduction?: string | null;
  /**
   * 링크 URL (http(s), 최대 2048자, 빈 문자열이면 제거)
   * @nullable
   */
  linkUrl?: string | null;
  /**
   * 프로필 사진 URL (http(s), 최대 255자, 빈 문자열이면 제거)
   * @nullable
   */
  pictureUrl?: string | null;
}
