/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Forgather API
 * 당신을 위한 순간, 흩어지지 않게. Forgather
 * OpenAPI spec version: 2.0.0
 */

/**
 * 스페이스 수정 정보 (JSON, text/plain)
 */
export interface UpdateSpaceRequest {
  /**
   * 새로운 스페이스 이름
   * @maxLength 30
   * @nullable
   */
  name?: string | null;
  /**
   * 새로운 스페이스 설명
   * @maxLength 200
   * @nullable
   */
  description?: string | null;
  /**
   * 새로운 스페이스 공개여부
   * @nullable
   */
  isPublic?: boolean | null;
  /**
   * 새로운 인스타그램 아이디
   * @maxLength 30
   * @nullable
   */
  instagramUsername?: string | null;
  /**
   * 새로운 이메일
   * @maxLength 50
   * @nullable
   */
  email?: string | null;
  /**
   * 새로운 소개 링크 URL (표시 이름과 함께 입력, 빈 쌍으로 삭제)
   * @maxLength 2048
   * @nullable
   */
  linkUrl?: string | null;
  /**
   * 새로운 소개 링크 표시 이름 (URL과 함께 입력)
   * @maxLength 30
   * @nullable
   */
  linkName?: string | null;
  /** 스페이스 사진 삭제 여부 */
  isDeletePhoto?: boolean;
  deletingPhoto?: boolean;
}
