/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Forgather API
 * 당신을 위한 순간, 흩어지지 않게. Forgather
 * OpenAPI spec version: 2.0.0
 */
import type { RegisterProductPhotoRequest } from './registerProductPhotoRequest';

export interface UpdateProductRequest {
  /**
   * 작품명
   * @maxLength 50
   */
  title?: string;
  /**
   * 작품 카테고리
   * @maxLength 20
   */
  category?: string;
  /**
   * 작가명
   * @maxLength 35
   */
  authorName?: string;
  /**
   * 작품 설명
   * @maxLength 2000
   */
  description?: string;
  /**
   * 임베드 영상 링크
   * @maxLength 512
   */
  videoUrl?: string;
  /** 영상이 사진 뒤에 오는지 여부 */
  isVideoAfterPhoto?: boolean;
  /** 삭제할 작품 사진 목록 */
  deletePhotoIds?: number[];
  /** 새로 업로드한 작품 사진 목록 */
  newPhotos?: RegisterProductPhotoRequest[];
}
