/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Forgather API
 * 당신을 위한 순간, 흩어지지 않게. Forgather
 * OpenAPI spec version: 2.0.0
 */

/**
 * 업로드 파일 목록
 */
export interface UploadFileRequest {
  /**
   * 업로드 파일 이름 (UUID.확장자)
   * @pattern ^[^/\\]+\.[a-z0-9]+$
   */
  fileName: string;
  /**
   * 업로드 파일 크기 (바이트)
   * @maximum 20971520
   */
  size: number;
}
