/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SignUpIndexRouteImport } from './routes/sign-up/index'
import { Route as LoginIndexRouteImport } from './routes/login/index'
import { Route as CreateExhibitionIndexRouteImport } from './routes/create-exhibition/index'
import { Route as NewGuestbookGuestbookIdRouteImport } from './routes/new-guestbook/$guestbookId'
import { Route as SpacesSpaceIdGuestbookRouteImport } from './routes/spaces/$spaceId/guestbook'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SignUpIndexRoute = SignUpIndexRouteImport.update({
  id: '/sign-up/',
  path: '/sign-up/',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginIndexRoute = LoginIndexRouteImport.update({
  id: '/login/',
  path: '/login/',
  getParentRoute: () => rootRouteImport,
} as any)
const CreateExhibitionIndexRoute = CreateExhibitionIndexRouteImport.update({
  id: '/create-exhibition/',
  path: '/create-exhibition/',
  getParentRoute: () => rootRouteImport,
} as any)
const NewGuestbookGuestbookIdRoute = NewGuestbookGuestbookIdRouteImport.update({
  id: '/new-guestbook/$guestbookId',
  path: '/new-guestbook/$guestbookId',
  getParentRoute: () => rootRouteImport,
} as any)
const SpacesSpaceIdGuestbookRoute = SpacesSpaceIdGuestbookRouteImport.update({
  id: '/spaces/$spaceId/guestbook',
  path: '/spaces/$spaceId/guestbook',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/new-guestbook/$guestbookId': typeof NewGuestbookGuestbookIdRoute
  '/create-exhibition/': typeof CreateExhibitionIndexRoute
  '/login/': typeof LoginIndexRoute
  '/sign-up/': typeof SignUpIndexRoute
  '/spaces/$spaceId/guestbook': typeof SpacesSpaceIdGuestbookRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/new-guestbook/$guestbookId': typeof NewGuestbookGuestbookIdRoute
  '/create-exhibition': typeof CreateExhibitionIndexRoute
  '/login': typeof LoginIndexRoute
  '/sign-up': typeof SignUpIndexRoute
  '/spaces/$spaceId/guestbook': typeof SpacesSpaceIdGuestbookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/new-guestbook/$guestbookId': typeof NewGuestbookGuestbookIdRoute
  '/create-exhibition/': typeof CreateExhibitionIndexRoute
  '/login/': typeof LoginIndexRoute
  '/sign-up/': typeof SignUpIndexRoute
  '/spaces/$spaceId/guestbook': typeof SpacesSpaceIdGuestbookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/new-guestbook/$guestbookId'
    | '/create-exhibition/'
    | '/login/'
    | '/sign-up/'
    | '/spaces/$spaceId/guestbook'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/new-guestbook/$guestbookId'
    | '/create-exhibition'
    | '/login'
    | '/sign-up'
    | '/spaces/$spaceId/guestbook'
  id:
    | '__root__'
    | '/'
    | '/new-guestbook/$guestbookId'
    | '/create-exhibition/'
    | '/login/'
    | '/sign-up/'
    | '/spaces/$spaceId/guestbook'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  NewGuestbookGuestbookIdRoute: typeof NewGuestbookGuestbookIdRoute
  CreateExhibitionIndexRoute: typeof CreateExhibitionIndexRoute
  LoginIndexRoute: typeof LoginIndexRoute
  SignUpIndexRoute: typeof SignUpIndexRoute
  SpacesSpaceIdGuestbookRoute: typeof SpacesSpaceIdGuestbookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-up/': {
      id: '/sign-up/'
      path: '/sign-up'
      fullPath: '/sign-up/'
      preLoaderRoute: typeof SignUpIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login/': {
      id: '/login/'
      path: '/login'
      fullPath: '/login/'
      preLoaderRoute: typeof LoginIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/create-exhibition/': {
      id: '/create-exhibition/'
      path: '/create-exhibition'
      fullPath: '/create-exhibition/'
      preLoaderRoute: typeof CreateExhibitionIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/new-guestbook/$guestbookId': {
      id: '/new-guestbook/$guestbookId'
      path: '/new-guestbook/$guestbookId'
      fullPath: '/new-guestbook/$guestbookId'
      preLoaderRoute: typeof NewGuestbookGuestbookIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/spaces/$spaceId/guestbook': {
      id: '/spaces/$spaceId/guestbook'
      path: '/spaces/$spaceId/guestbook'
      fullPath: '/spaces/$spaceId/guestbook'
      preLoaderRoute: typeof SpacesSpaceIdGuestbookRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  NewGuestbookGuestbookIdRoute: NewGuestbookGuestbookIdRoute,
  CreateExhibitionIndexRoute: CreateExhibitionIndexRoute,
  LoginIndexRoute: LoginIndexRoute,
  SignUpIndexRoute: SignUpIndexRoute,
  SpacesSpaceIdGuestbookRoute: SpacesSpaceIdGuestbookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
