/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as LoginIndexRouteImport } from './routes/login/index'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedNewGuestbooksRouteImport } from './routes/_authenticated/new-guestbooks'
import { Route as AuthenticatedSignUpIndexRouteImport } from './routes/_authenticated/sign-up/index'
import { Route as AuthenticatedMyPageIndexRouteImport } from './routes/_authenticated/my-page/index'
import { Route as AuthenticatedHomeIndexRouteImport } from './routes/_authenticated/home/index'
import { Route as AuthenticatedCreateExhibitionIndexRouteImport } from './routes/_authenticated/create-exhibition/index'
import { Route as AuthenticatedSpacesSpaceIdRouteImport } from './routes/_authenticated/spaces/$spaceId'
import { Route as AuthenticatedSignUpCompleteRouteImport } from './routes/_authenticated/sign-up/complete'
import { Route as AuthenticatedNewGuestbookGuestbookIdRouteImport } from './routes/_authenticated/new-guestbook/$guestbookId'
import { Route as AuthenticatedMyPageEditRouteImport } from './routes/_authenticated/my-page/edit'
import { Route as AuthenticatedSpacesSpaceIdIndexRouteImport } from './routes/_authenticated/spaces/$spaceId/index'
import { Route as AuthenticatedSpacesSpaceIdGuestbookRouteImport } from './routes/_authenticated/spaces/$spaceId/guestbook'

const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginIndexRoute = LoginIndexRouteImport.update({
  id: '/login/',
  path: '/login/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedNewGuestbooksRoute =
  AuthenticatedNewGuestbooksRouteImport.update({
    id: '/new-guestbooks',
    path: '/new-guestbooks',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedSignUpIndexRoute =
  AuthenticatedSignUpIndexRouteImport.update({
    id: '/sign-up/',
    path: '/sign-up/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedMyPageIndexRoute =
  AuthenticatedMyPageIndexRouteImport.update({
    id: '/my-page/',
    path: '/my-page/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedHomeIndexRoute = AuthenticatedHomeIndexRouteImport.update({
  id: '/home/',
  path: '/home/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedCreateExhibitionIndexRoute =
  AuthenticatedCreateExhibitionIndexRouteImport.update({
    id: '/create-exhibition/',
    path: '/create-exhibition/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedSpacesSpaceIdRoute =
  AuthenticatedSpacesSpaceIdRouteImport.update({
    id: '/spaces/$spaceId',
    path: '/spaces/$spaceId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedSignUpCompleteRoute =
  AuthenticatedSignUpCompleteRouteImport.update({
    id: '/sign-up/complete',
    path: '/sign-up/complete',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedNewGuestbookGuestbookIdRoute =
  AuthenticatedNewGuestbookGuestbookIdRouteImport.update({
    id: '/new-guestbook/$guestbookId',
    path: '/new-guestbook/$guestbookId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedMyPageEditRoute = AuthenticatedMyPageEditRouteImport.update({
  id: '/my-page/edit',
  path: '/my-page/edit',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSpacesSpaceIdIndexRoute =
  AuthenticatedSpacesSpaceIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedSpacesSpaceIdRoute,
  } as any)
const AuthenticatedSpacesSpaceIdGuestbookRoute =
  AuthenticatedSpacesSpaceIdGuestbookRouteImport.update({
    id: '/guestbook',
    path: '/guestbook',
    getParentRoute: () => AuthenticatedSpacesSpaceIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/new-guestbooks': typeof AuthenticatedNewGuestbooksRoute
  '/login/': typeof LoginIndexRoute
  '/my-page/edit': typeof AuthenticatedMyPageEditRoute
  '/new-guestbook/$guestbookId': typeof AuthenticatedNewGuestbookGuestbookIdRoute
  '/sign-up/complete': typeof AuthenticatedSignUpCompleteRoute
  '/spaces/$spaceId': typeof AuthenticatedSpacesSpaceIdRouteWithChildren
  '/create-exhibition/': typeof AuthenticatedCreateExhibitionIndexRoute
  '/home/': typeof AuthenticatedHomeIndexRoute
  '/my-page/': typeof AuthenticatedMyPageIndexRoute
  '/sign-up/': typeof AuthenticatedSignUpIndexRoute
  '/spaces/$spaceId/guestbook': typeof AuthenticatedSpacesSpaceIdGuestbookRoute
  '/spaces/$spaceId/': typeof AuthenticatedSpacesSpaceIdIndexRoute
}
export interface FileRoutesByTo {
  '/new-guestbooks': typeof AuthenticatedNewGuestbooksRoute
  '/': typeof AuthenticatedIndexRoute
  '/login': typeof LoginIndexRoute
  '/my-page/edit': typeof AuthenticatedMyPageEditRoute
  '/new-guestbook/$guestbookId': typeof AuthenticatedNewGuestbookGuestbookIdRoute
  '/sign-up/complete': typeof AuthenticatedSignUpCompleteRoute
  '/create-exhibition': typeof AuthenticatedCreateExhibitionIndexRoute
  '/home': typeof AuthenticatedHomeIndexRoute
  '/my-page': typeof AuthenticatedMyPageIndexRoute
  '/sign-up': typeof AuthenticatedSignUpIndexRoute
  '/spaces/$spaceId/guestbook': typeof AuthenticatedSpacesSpaceIdGuestbookRoute
  '/spaces/$spaceId': typeof AuthenticatedSpacesSpaceIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/_authenticated/new-guestbooks': typeof AuthenticatedNewGuestbooksRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/login/': typeof LoginIndexRoute
  '/_authenticated/my-page/edit': typeof AuthenticatedMyPageEditRoute
  '/_authenticated/new-guestbook/$guestbookId': typeof AuthenticatedNewGuestbookGuestbookIdRoute
  '/_authenticated/sign-up/complete': typeof AuthenticatedSignUpCompleteRoute
  '/_authenticated/spaces/$spaceId': typeof AuthenticatedSpacesSpaceIdRouteWithChildren
  '/_authenticated/create-exhibition/': typeof AuthenticatedCreateExhibitionIndexRoute
  '/_authenticated/home/': typeof AuthenticatedHomeIndexRoute
  '/_authenticated/my-page/': typeof AuthenticatedMyPageIndexRoute
  '/_authenticated/sign-up/': typeof AuthenticatedSignUpIndexRoute
  '/_authenticated/spaces/$spaceId/guestbook': typeof AuthenticatedSpacesSpaceIdGuestbookRoute
  '/_authenticated/spaces/$spaceId/': typeof AuthenticatedSpacesSpaceIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/new-guestbooks'
    | '/login/'
    | '/my-page/edit'
    | '/new-guestbook/$guestbookId'
    | '/sign-up/complete'
    | '/spaces/$spaceId'
    | '/create-exhibition/'
    | '/home/'
    | '/my-page/'
    | '/sign-up/'
    | '/spaces/$spaceId/guestbook'
    | '/spaces/$spaceId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/new-guestbooks'
    | '/'
    | '/login'
    | '/my-page/edit'
    | '/new-guestbook/$guestbookId'
    | '/sign-up/complete'
    | '/create-exhibition'
    | '/home'
    | '/my-page'
    | '/sign-up'
    | '/spaces/$spaceId/guestbook'
    | '/spaces/$spaceId'
  id:
    | '__root__'
    | '/_authenticated'
    | '/_authenticated/new-guestbooks'
    | '/_authenticated/'
    | '/login/'
    | '/_authenticated/my-page/edit'
    | '/_authenticated/new-guestbook/$guestbookId'
    | '/_authenticated/sign-up/complete'
    | '/_authenticated/spaces/$spaceId'
    | '/_authenticated/create-exhibition/'
    | '/_authenticated/home/'
    | '/_authenticated/my-page/'
    | '/_authenticated/sign-up/'
    | '/_authenticated/spaces/$spaceId/guestbook'
    | '/_authenticated/spaces/$spaceId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginIndexRoute: typeof LoginIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login/': {
      id: '/login/'
      path: '/login'
      fullPath: '/login/'
      preLoaderRoute: typeof LoginIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/new-guestbooks': {
      id: '/_authenticated/new-guestbooks'
      path: '/new-guestbooks'
      fullPath: '/new-guestbooks'
      preLoaderRoute: typeof AuthenticatedNewGuestbooksRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/sign-up/': {
      id: '/_authenticated/sign-up/'
      path: '/sign-up'
      fullPath: '/sign-up/'
      preLoaderRoute: typeof AuthenticatedSignUpIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/my-page/': {
      id: '/_authenticated/my-page/'
      path: '/my-page'
      fullPath: '/my-page/'
      preLoaderRoute: typeof AuthenticatedMyPageIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/home/': {
      id: '/_authenticated/home/'
      path: '/home'
      fullPath: '/home/'
      preLoaderRoute: typeof AuthenticatedHomeIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/create-exhibition/': {
      id: '/_authenticated/create-exhibition/'
      path: '/create-exhibition'
      fullPath: '/create-exhibition/'
      preLoaderRoute: typeof AuthenticatedCreateExhibitionIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/spaces/$spaceId': {
      id: '/_authenticated/spaces/$spaceId'
      path: '/spaces/$spaceId'
      fullPath: '/spaces/$spaceId'
      preLoaderRoute: typeof AuthenticatedSpacesSpaceIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/sign-up/complete': {
      id: '/_authenticated/sign-up/complete'
      path: '/sign-up/complete'
      fullPath: '/sign-up/complete'
      preLoaderRoute: typeof AuthenticatedSignUpCompleteRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/new-guestbook/$guestbookId': {
      id: '/_authenticated/new-guestbook/$guestbookId'
      path: '/new-guestbook/$guestbookId'
      fullPath: '/new-guestbook/$guestbookId'
      preLoaderRoute: typeof AuthenticatedNewGuestbookGuestbookIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/my-page/edit': {
      id: '/_authenticated/my-page/edit'
      path: '/my-page/edit'
      fullPath: '/my-page/edit'
      preLoaderRoute: typeof AuthenticatedMyPageEditRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/spaces/$spaceId/': {
      id: '/_authenticated/spaces/$spaceId/'
      path: '/'
      fullPath: '/spaces/$spaceId/'
      preLoaderRoute: typeof AuthenticatedSpacesSpaceIdIndexRouteImport
      parentRoute: typeof AuthenticatedSpacesSpaceIdRoute
    }
    '/_authenticated/spaces/$spaceId/guestbook': {
      id: '/_authenticated/spaces/$spaceId/guestbook'
      path: '/guestbook'
      fullPath: '/spaces/$spaceId/guestbook'
      preLoaderRoute: typeof AuthenticatedSpacesSpaceIdGuestbookRouteImport
      parentRoute: typeof AuthenticatedSpacesSpaceIdRoute
    }
  }
}

interface AuthenticatedSpacesSpaceIdRouteChildren {
  AuthenticatedSpacesSpaceIdGuestbookRoute: typeof AuthenticatedSpacesSpaceIdGuestbookRoute
  AuthenticatedSpacesSpaceIdIndexRoute: typeof AuthenticatedSpacesSpaceIdIndexRoute
}

const AuthenticatedSpacesSpaceIdRouteChildren: AuthenticatedSpacesSpaceIdRouteChildren =
  {
    AuthenticatedSpacesSpaceIdGuestbookRoute:
      AuthenticatedSpacesSpaceIdGuestbookRoute,
    AuthenticatedSpacesSpaceIdIndexRoute: AuthenticatedSpacesSpaceIdIndexRoute,
  }

const AuthenticatedSpacesSpaceIdRouteWithChildren =
  AuthenticatedSpacesSpaceIdRoute._addFileChildren(
    AuthenticatedSpacesSpaceIdRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedNewGuestbooksRoute: typeof AuthenticatedNewGuestbooksRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedMyPageEditRoute: typeof AuthenticatedMyPageEditRoute
  AuthenticatedNewGuestbookGuestbookIdRoute: typeof AuthenticatedNewGuestbookGuestbookIdRoute
  AuthenticatedSignUpCompleteRoute: typeof AuthenticatedSignUpCompleteRoute
  AuthenticatedSpacesSpaceIdRoute: typeof AuthenticatedSpacesSpaceIdRouteWithChildren
  AuthenticatedCreateExhibitionIndexRoute: typeof AuthenticatedCreateExhibitionIndexRoute
  AuthenticatedHomeIndexRoute: typeof AuthenticatedHomeIndexRoute
  AuthenticatedMyPageIndexRoute: typeof AuthenticatedMyPageIndexRoute
  AuthenticatedSignUpIndexRoute: typeof AuthenticatedSignUpIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedNewGuestbooksRoute: AuthenticatedNewGuestbooksRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedMyPageEditRoute: AuthenticatedMyPageEditRoute,
  AuthenticatedNewGuestbookGuestbookIdRoute:
    AuthenticatedNewGuestbookGuestbookIdRoute,
  AuthenticatedSignUpCompleteRoute: AuthenticatedSignUpCompleteRoute,
  AuthenticatedSpacesSpaceIdRoute: AuthenticatedSpacesSpaceIdRouteWithChildren,
  AuthenticatedCreateExhibitionIndexRoute:
    AuthenticatedCreateExhibitionIndexRoute,
  AuthenticatedHomeIndexRoute: AuthenticatedHomeIndexRoute,
  AuthenticatedMyPageIndexRoute: AuthenticatedMyPageIndexRoute,
  AuthenticatedSignUpIndexRoute: AuthenticatedSignUpIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginIndexRoute: LoginIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
