/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CreateExhibitionIndexRouteImport } from './routes/create-exhibition/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CreateExhibitionIndexRoute = CreateExhibitionIndexRouteImport.update({
  id: '/create-exhibition/',
  path: '/create-exhibition/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/create-exhibition/': typeof CreateExhibitionIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/create-exhibition': typeof CreateExhibitionIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/create-exhibition/': typeof CreateExhibitionIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/create-exhibition/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/create-exhibition'
  id: '__root__' | '/' | '/create-exhibition/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CreateExhibitionIndexRoute: typeof CreateExhibitionIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/create-exhibition/': {
      id: '/create-exhibition/'
      path: '/create-exhibition'
      fullPath: '/create-exhibition/'
      preLoaderRoute: typeof CreateExhibitionIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CreateExhibitionIndexRoute: CreateExhibitionIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
